name: Deploy Waitingway.Server
on: 
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: dotnet publish
      run: dotnet publish Waitingway.Server -c Release -o deploy -r linux-x64
    - name: SCP Command to Transfer Files
      uses: appleboy/scp-action@v0.1.2
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        source: 'deploy/*'
        target: '/var/www/waitingway'
        strip_components: 1
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: sudo /usr/sbin/waitingway-deploy
